import org.celllife.iquit.application.domain.campaignselector.RulesContext
 
rule "Select All/Not drinker campaign"
	no-loop true 
when
     $params : RulesContext(get("drinks") == "no");
then
     System.out.println("Bob is assigned to not drinking campaign");
     $params.setReturnValue("no_drinks");
     update($params);
end

rule "Select Male/Drinker campaign"
	no-loop true 
when
     $params : RulesContext(get("gender") == "male" && get("drinks") == "yes");
     
then
     System.out.println("Bob is assigned to male drinking campaign");
     $params.setReturnValue("male_drinks");
     update($params);
end

rule "Select Female/Drinker campaign"
	no-loop true 
when
     $params : RulesContext(get("gender") == "female" && get("drinks") == "yes");
     
then
     System.out.println("Bob is assigned to female drinking campaign");
     $params.setReturnValue("female_drinks");
     update($params);
end