import org.celllife.iquit.framework.interfaces.validator.FormValidationContext
import java.util.Calendar
 
rule "Check year of birth is numbers"
	no-loop true 
when
     $params : FormValidationContext(((String)get("year")).matches(".*\\d.*") == false);
then
     $params.setValidationError("Please enter only numbers for your year of birth.");
     update($params);
end

rule "Check year of birth is only 4 digits"
	no-loop true 
when
     $params : FormValidationContext(((String)get("year")).length != 4);
then
     $params.setValidationError("Please enter four digits for your year of birth (yyyy).");
     update($params);
end

rule "Check age is greater than 18"
	no-loop true 
when
     $params : FormValidationContext(((String)get("year")).matches(".*\\d.*") == true, (Calendar.getInstance().get(Calendar.YEAR) - Integer.parseInt((String)get("year"))) < 18);
then
     $params.setValidationError("Unfortunately you must be 18 or over to use this service.");
     update($params);
end

rule "Validate mobile number"
	no-loop true 
when
     $params : FormValidationContext(((String)get("msisdn")).matches("^27[0-9]{9}$") == false);
then
     $params.setValidationError("Please fill in your cellphone number starting with 27.");
     update($params);
end